In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df=pd.read_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/raw/05_category_inflows.csv")
df.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [3]:
df.dtypes

month                object
category             object
net_inflow_crore    float64
dtype: object

In [4]:
df.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [5]:
df.duplicated().sum() ## there are no duplicates 
# for deleting the duplicates
df.drop_duplicates(inplace=True)

In [6]:
## saving cleaned data to processed data
df.to_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/processed/05_cleaned_category_inflows.csv",index=False)