In [2]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [16]:
nav_history = pd.read_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/raw/02_nav_history.csv")
nav_history.head(5)

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [44]:
#Checking the data types of the column in the DataFrame
print("Shape:", nav_history.shape)
print("Data Types:\n",nav_history.dtypes)

Shape: (46000, 3)
Data Types:
 amfi_code      int64
date          object
nav          float64
dtype: object

In [45]:
#Changing the Data Type of the date column to datetime format
nav_history["date"] = pd.to_datetime(nav_history["date"],errors='coerce')
nav_history.head(25)

    amfi_code       date      nav
0      119551 2022-01-03  54.3856
1      119551 2022-01-04  54.3474
2      119551 2022-01-05  54.6869
3      119551 2022-01-06  55.4550
4      119551 2022-01-07  55.3692
5      119551 2022-01-10  55.2835
6      119551 2022-01-11  56.0878
7      119551 2022-01-12  56.4978
8      119551 2022-01-13  56.2934
9      119551 2022-01-14  56.5926
10     119551 2022-01-17  56.3908
11     119551 2022-01-18  56.1887
12     119551 2022-01-19  56.3378
13     119551 2022-01-20  55.4237
14     119551 2022-01-21  54.6151
15     119551 2022-01-24  54.3730
16     119551 2022-01-25  53.9173
17     119551 2022-01-26  54.0948
18     119551 2022-01-27  53.6911
19     119551 2022-01-28  53.0538
20     119551 2022-01-31  53.7718
21     119551 2022-02-01  53.6925
22     119551 2022-02-02  53.7522
23     119551 2022-02-03  53.1084
24     119551 2022-02-04  52.8813

In [46]:
# Checking Dublicates and droping them if any
nav_history.duplicated().sum() #there are no dublicates in the data

np.int64(0)

In [52]:
#Validate
invalid_nav=nav_history[nav_history["nav"]<0]
print("Total number od invalid nav:",len(invalid_nav))
# There are no invalid nav values in the data.

Total number od invalid nav: 0

In [48]:
#Forward fill missing nav for weekends and holidays
nav_history["nav"]=nav_history.groupby(["amfi_code"])["nav"].ffill()

In [56]:
nav_history.to_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/processed/02_cleaned_nav_history.csv",index=False)

In [53]:
nav_history.sample(10)

       amfi_code       date       nav
37952     102887 2022-01-05  188.0701
44445     149323 2024-11-11  188.9889
36919     102886 2022-06-17  129.4097
4908      119120 2023-03-09   43.8675
9577      125498 2023-06-14  131.2271
11704     120503 2022-10-14   73.4455
8428      100033 2023-06-15  144.0624
19426     118633 2025-12-09   79.7797
43746     149323 2022-03-08   78.3941
17895     118632 2024-06-24   68.6839

In [3]:
df=pd.read_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/raw/01_fund_master.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

In [11]:
df.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')